server:
  port: 8081


person:
  lastName: zhangsan
  age: 19
  boss: false
  birth: 2017/12/12
  maps: {k1: v1,k2: v2}
  lists:
    - list
    - zhouliu
  dog:
    name: 小狗
    age: 2


userInfo: 123